# Generated by Django 2.2.2 on 2019-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('restriction', models.IntegerField(blank=True)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
