# Generated by Django 2.1.7 on 2019-07-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restriction',
            field=models.BooleanField(),
        ),
    ]
