# Generated by Django 2.1.7 on 2019-07-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20190721_0014'),
        ('product', '0005_auto_20190720_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.Node_father'),
        ),
    ]
