# Generated by Django 2.1.7 on 2019-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
