# Generated by Django 2.2.3 on 2019-08-02 22:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_red', models.BooleanField(default=True)),
                ('name', models.TextField(blank=True, max_length=500)),
                ('percentage_commission', models.IntegerField()),
                ('id_father', models.IntegerField(null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node_father',
            fields=[
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.Nodes', unique=True)),
                ('initial_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('final_date', models.DateField(null=True)),
                ('generateCode', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_commision', models.IntegerField()),
                ('type_payment', models.TextField(blank=True, max_length=500)),
                ('type_commission', models.TextField(blank=True, max_length=500)),
                ('current_balance', models.IntegerField(null=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
