# Generated by Django 2.2.2 on 2019-07-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_father',
            name='generateCode',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nodes',
            name='id_father',
            field=models.IntegerField(null=True),
        ),
    ]
