# Generated by Django 2.1.7 on 2019-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_father',
            name='generateCode',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
