# Generated by Django 2.1.7 on 2019-07-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='is_red',
            field=models.BooleanField(default=True),
        ),
    ]
