# Generated by Django 2.1.7 on 2019-07-21 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20190720_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_father',
            name='final_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='node_father',
            name='initial_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
