# Generated by Django 2.1.7 on 2019-07-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_father_generatecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='id_father',
            field=models.IntegerField(null=True),
        ),
    ]
