# Generated by Django 2.1.7 on 2019-07-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20190721_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_father',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.Nodes'),
        ),
    ]
