# Generated by Django 2.1.7 on 2019-07-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_auto_20190729_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_father',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node_father',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.Nodes'),
        ),
    ]
