# Generated by Django 2.2.2 on 2019-07-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20190729_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_father',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.Nodes'),
        ),
    ]
