# Generated by Django 2.2.2 on 2019-07-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_auto_20190729_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_father',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node_father',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.Nodes'),
        ),
    ]
