# Generated by Django 2.2.2 on 2019-07-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_auto_20190729_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_father',
            name='id',
        ),
        migrations.AlterField(
            model_name='node_father',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.Nodes'),
        ),
    ]
