# Generated by Django 2.2.2 on 2019-07-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_auto_20190729_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_father',
            name='id',
            field=models.AutoField(auto_created=True, default='null', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node_father',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.Nodes'),
        ),
    ]
